# Generated by Django 5.2.17 on 2026-08-31 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('revision_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='articles.article')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='sections.section')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAlertDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_at', models.DateTimeField()),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_dismissals', to='articles.article')),
                ('dismissed_by', models.ForeignKey(limit_choices_to={'role': 'editor'}, on_delete=django.db.models.deletion.PROTECT, related_name='dismissed_article_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dismissed_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status Change'), ('revision_opened', 'Revision Opened'), ('comment', 'Comment')], db_index=True, max_length=32)),
                ('old_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published')], max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published')], max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_events', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='articles.article')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('revision_of')), _negated=True), name='articles_revision_of_cannot_point_to_self'),
        ),
        migrations.AddConstraint(
            model_name='articlealertdismissal',
            constraint=models.UniqueConstraint(fields=('article', 'publish_at'), name='articles_alert_dismissal_unique_article_publish_at'),
        ),
    ]
